### ISSUE TITLE
온도 정보가 표기되지 않습니다.

### ISSUE THREAD

**Issue by bigstark** [YuChocopie/Olaf#178]
![kakaotalk_photo_2019-03-05-12-41-28](https://user-images.githubusercontent.com/3222096/53779606-070b0700-3f44-11e9-877e-41c0df0d42f8.jpeg)

**Comment by bigstark** [comment]
@YuChocopie @jujinkim @pengin7384

#180 에서 해결될 예정입니다.

**Comment by jujinkim** [comment]
#180 merged
